### ISSUE TITLE
Logging configuration in src/main/tomcat/conf/logging.properties is ignored

### ISSUE THREAD

**Issue by jhorstmann** [t7mp/t7mp#28]
I wanted to increase the log level for my own webapp by adding a line to src/main/tomcat/conf/logging.properties like this

```
net.jhorstmann.level = FINE
```

The file gets copied to target/tomcat/conf but the configuration seems to be ignored. I guess the logging configuration is normally set by the tomcat startup scripts by specifying the system property `java.util.logging.config.file`. I also tried adding the following to the plugin configuration, but also without any effect:

```
<systemProperties>
    <systemProperty>
        <key>java.util.logging.config.file</key>
        <value>${basedir}/src/main/tomcat/conf/logging.properties</value>
    </systemProperty>
</systemProperties>
```

**Comment by t7mp** [comment]
Hello jhorstmann,

please try it again with the latest version (0.9.8-SNAPSHOT) of the plugin. Please run it with the following command 't7:run-forked'. That is a new goal that starts an instance in an separate vm. So the logging-configuration should work as expected.

Be aware, it's a snapshot. Please send us any issue that pop up. And it would be fine if you test it on windows-os because I have no windows installed on my machines.

Cheers
Jörg

**Comment by jhorstmann** [comment]
Thanks, I finally got around to test the current snapshot (3ac3d3b9fda9234385e2c4dbba182a05169f0697). I dont't have any windows here either, my test was on Ubuntu 11.04. Sadly the plugin throws an Exception on startup with the following stacktrace. The `target/tomcat/bin` directory exists, but it does not contain any file starting with `setenv`, the usual shell scripts like `catalina.sh` exist though.

```
[INFO] --- maven-t7-plugin:0.9.8-SNAPSHOT:run-forked (default-cli) @ i18n-sample-webapp ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.234s
[INFO] Finished at: Thu Aug 25 00:27:59 CEST 2011
[INFO] Final Memory: 16M/119M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.googlecode.t7mp:maven-t7-plugin:0.9.8-SNAPSHOT:run-forked (default-cli) on project i18n-sample-webapp: Execution default-cli of goal com.googlecode.t7mp:maven-t7-plugin:0.9.8-SNAPSHOT:run-forked failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.googlecode.t7mp:maven-t7-plugin:0.9.8-SNAPSHOT:run-forked (default-cli) on project i18n-sample-webapp: Execution default-cli of goal com.googlecode.t7mp:maven-t7-plugin:0.9.8-SNAPSHOT:run-forked failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.googlecode.t7mp:maven-t7-plugin:0.9.8-SNAPSHOT:run-forked failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: java.lang.NullPointerException
        at com.googlecode.t7mp.steps.resources.CopySetenvScriptStep.execute(CopySetenvScriptStep.java:34)
        at com.googlecode.t7mp.steps.DefaultStepSequence.execute(DefaultStepSequence.java:33)
        at com.googlecode.t7mp.RunForkedMojo.execute(RunForkedMojo.java:36)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        ... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by t7mp** [comment]
Hi Jörn,

sorry for running in this NPE and thanks for the stacktrace. Seems to me that I have to write more tests ;-)

The 'setenv.sh' or 'setenv.bat' does not come with the tomcat-distribution. Nevertheless it is called by default in the 'catalina.sh' or 'catalina.bat' if it exist. People can use it to define some environment settings (memory, jmx, etc. ).

MfG
Jörg

**Comment by t7mp** [comment]
Hi Jörn,

I fixed the NPE. So maybe you can update your fork (or clone directly from the current master)  and run a full build of the plugin. It would be cool when you can build it with integration-tests enabled. You can do that by using the following command: 'mvn clean install -Prun-its'.
After the normal compile -- test cycle some integrationtests are executed. They use the configuration from 'src/it'. Some test will fail but interesting for you are the configurations '7.0.19-background' and '7.0.19-background_28'. The first configuration provides an 'setenv.sh'-file the second will not. Both have 'logging.properties' configured with a logger in level 'FINE'. You will find the logs for both under 'target/it/7.0.19-background****/build.log'. So you can verify that no NPE occurred and you should see logging-output of the FINE-logger. Thats what you are interested in, right? ;-)

If you have any further questions or maybe (but hopefully not) new stacktraces, please post them. So we can improve the  plugin for users need.

These changes are on the master-branch only for now. I did not deploy the latest changes to a snapshot repository. I will do that later today.

MfG
Jörg

**Comment by jhorstmann** [comment]
Hi Jörg,

Thanks for the quick answer. With the new version my test app is now running fine and logging at the configured levels. The integration tests for tomcat 7.0.19 are also succeeding and logging is working. I only noticed that some integration tests for tomcat 6.0.x are failing but it seems that is only because the tomcat bundles are not yet in the maven repository.

```
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 9, Failed: 3, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  6.0.28/pom.xml
[ERROR] *  6.0.32/pom.xml
[ERROR] *  6.0.29/pom.xml
```

 I'm closing this issue as fixed now.

Regards
  Jörn
